### ISSUE TITLE
Crash on world generation

### ISSUE THREAD

**Issue by ghost** [ZeekDaGeek/worldworldpack-public#37]
This is the error log I have tried to make a Biomes o' plenty world and a standard world and they both have the same error

[17:33:46] [Client thread/ERROR] [FML]: The fluid registry is corrupted. A fluid ganymedes01.aobd.recipes.RecipesModule$MoltenMetal aobdyellorium is not properly registered. The mod that registered this is broken
[17:33:51] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:276) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher$1.run(OneSixLauncher.java:351) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: The fluid registry is corrupted
    at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:297) ~[FluidRegistry.class:?]
    at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:327) ~[FluidRegistry.class:?]
    at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:315) ~[ForgeModContainer.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375) ~[FMLCommonHandler.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209) ~[ayq.class:?]
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081) ~[bao.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
    ... 15 more
[17:33:51] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// But it works on my machine.

Time: 8/5/15 5:33 PM
Description: Updating screen events

java.lang.IllegalStateException: The fluid registry is corrupted
    at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:297)
    at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:327)
    at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:315)
    at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
    at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:276)
    at org.multimc.onesix.OneSixLauncher$1.run(OneSixLauncher.java:351)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:297)
    at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:327)
    at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:315)
    at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
    at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:276)
    at org.multimc.onesix.OneSixLauncher$1.run(OneSixLauncher.java:351)

**Comment by Ezrahk** [comment]
I'm getting this same error as well, fresh install of the pack. I get the same generic crash report as well but I was looking through the log and it seems that the AOBD recipe for molten yellorium is not being registered properly.

[15:04:30] [Client thread/ERROR] [FML]: The fluid registry is corrupted. A fluid ganymedes01.aobd.recipes.RecipesModule$MoltenMetal aobdyellorium is not properly registered. The mod that registered this is broken

Edit: It is an issue with AOBD 2.8.0. I was able to create a world without a problem disabling it. Upgrading to AOBD 2.8.1 solved the fluid registry problem for me.

**Comment by TheSilverCheetah** [comment]
Had the exact same error after fresh install. Can confirm that Ezrahk's solution of updating AOBD fixes the issue. Thanks for that Ezrahk <3

**Comment by ghost** [comment]
Thanks for that Ezrahk

**Comment by ZeekDaGeek** [comment]
Version 0.5.0a is available now and should fix this issue.

http://tinyurl.com/wwpack
