### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by SpectacularNumbers** [ZeekDaGeek/worldworldpack-public#7]
Server crashes when I come online (told this by nskid). The only thing I've been doing is moving stuff from chests into my ae system MANUALLY, and running a pulverizer and an electric furnace. Me and sgarr also have an iron farm, but its been doing fine, in fact I keep checking on it before the server crashes. May be pneumatic craft related, because I started that a few days ago. Could be mechanism, we have a few windmills and machines around. Also could be enhanced portals, but I honestly don't know. Also the first time it crashed, I was using a sag mill. Could be useful.

Powered Spawner spawning carminate golems might be crashing it.

Could someone please check the crash logs?

**Comment by SpectacularNumbers** [comment]
Me and sgarr also have an iron farm, but its been doing fine, in fact I keep checking on it before the server crashes. May be pneumatic craft related, because I started that a few days ago. Could be mechanism, we have a few windmills and machines around. Also could be enhanced portals, but I honestly don't know. :/

**Comment by ZeekDaGeek** [comment]
Yes, totally didn't care when I specifically removed a mod to try to help you and told you to tell me if the problem is fixed.

Try removing any Generators from Mekanism that you have. It's apparently related to the following:

```
java.lang.NoSuchFieldError: enableAmbientLighting
        at mekanism.generators.common.block.BlockGenerator.getLightValue(BlockGenerator.java:139)
        at net.minecraft.world.World.func_98179_a(World.java:2990)
        at net.minecraft.world.World.func_147463_c(World.java:3049)
        at net.minecraft.world.World.func_147451_t(World.java:2977)
        at net.minecraft.world.World.func_72903_x(World.java:2820)
        at net.minecraft.world.World.func_147456_g(World.java:2861)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:302)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by SpectacularNumbers** [comment]
Was talking about nskid before I posted this, i'll try and do it now. Thanks!

**Comment by Skid-Inc** [comment]
He's failed to mention that the last couple of server crashes also happened when he was on, last one was 10 minutes prior to me posting this, so around 21:20 GMT. Possibly more mek generators in the area, or maybe other mek machines causing it? I know the pentagon have the mek ore multiplying system ontop of their building so maybe that was / is the same bug. (They've not been on to confirm any extra crashes in there base).

**Comment by SpectacularNumbers** [comment]
What nskid said above, and if I think correctly, I was talking about nskid, not you zeek :P

**Comment by SpectacularNumbers** [comment]
Extra Info: Mekanism machines also known to cause crashes.
